services:
  legacy:
    build:
      context: .
      dockerfile: legacy.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src

  modern:
    build:
      context: .
      dockerfile: modern.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/app/src
